### ISSUE TITLE
Price difference

### ISSUE THREAD

**Issue by cpfxcl** [scottburlovich/pythonpancakes#2]
Hello
First of all, thank you very much for your API to consume data in Python.

Today I was testing it but there is a difference between the return price and the real price in PancakeSwap

I attach screenshots

`{'updated_at': 1622034328103,
 'data': {'name': 'PancakeSwap Token',
  'symbol': 'Cake',
  'price': '16.71025903658802895071381884442674',
  'price_BNB': '0.05104375696015457193635101802057258'}}`

![cake](https://user-images.githubusercontent.com/56266073/119665308-42829c00-be02-11eb-85ba-931f47a20adb.PNG)

So you can review it

**Comment by scottburlovich** [comment]
Hi, thanks for reporting!

I believe this issue lies with PancakeSwap's API, as my Python wrapper simply passes on the output - the updated_at timestamp indicates when the data was last updated on their side. 

There have been other reports of pricing issues recently with the PancakeSwap API, see https://github.com/pancakeswap/pancake-info-api/issues/53#issuecomment-849707635

I will keep an eye out for a resolution from their side and update.

**Comment by scottburlovich** [comment]
Following up - It appears that the issues have finally been resolved on the PancakeSwap side... There is no longer a price discrepancy between the API and their front end.

![image](https://user-images.githubusercontent.com/2328416/124961474-8664e580-dfeb-11eb-89e6-fe36246ded51.png)
![image](https://user-images.githubusercontent.com/2328416/124961503-941a6b00-dfeb-11eb-9c41-7617627aa62c.png)
